[package]
name = "macroquad-particles"
version = "0.2.0"
authors = ["Fedor Logachev <not.fl3@gmail.com>"]
edition = "2018"
license = "MIT/Apache-2.0"
description = """
Visual effects editor based on macroquad and megaui.
"""

[dependencies]
macroquad = "0.4.4"
nanoserde = { version = "0.1", optional = true }
